# Generated by Django 5.2.7 on 2025-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='payment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
