# Generated by Django 5.2.7 on 2025-10-29 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('Motorcycle', 'Motorcycle'), ('Van', 'Van')], default='Car', max_length=20),
        ),
    ]
