# Generated by Django 5.2.7 on 2025-11-12 06:47

import django_google_maps.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dropoff_location_coordinates',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_location_gmap',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location_coordinates',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_location_gmap',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True),
        ),
    ]
