# Generated by Django 5.2.7 on 2025-11-24 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_location_coordinates',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropoff_location_gmap',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location_coordinates',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='pickup_location_gmap',
        ),
        migrations.AddField(
            model_name='booking',
            name='dropoff_geolocation',
            field=models.CharField(default='0,0', max_length=50),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_geolocation',
            field=models.CharField(default='0,0', max_length=50),
        ),
    ]
