# Generated by Django 5.2.7 on 2025-12-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_remove_booking_dropoff_location_coordinates_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='deleted_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
